---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: uptime-ingressroute
  namespace: uptime-kuma
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`uptime.projectkube.com`)
      kind: Rule
      services:
        - name: uptime-kuma
          port: 3001

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-claim
  namespace: uptime-kuma
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi