apiVersion: v1
kind: ServiceAccount
metadata:
  name: reader

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: reader
rules:
- apiGroups: ["*"] # All API groups
  resources: ["*"] # All resources
  verbs: ["get", "list", "watch"]
- apiGroups: [""] # Core API group
  resources: ["pods"]
  verbs: ["delete"]
- apiGroups: ["apps"] 
  resources: ["deployments"]
  verbs: ["patch"] # Needed for restarts

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reader
  namespace: default
subjects:
- kind: ServiceAccount
  name: reader
  namespace: default
roleRef:
  kind: Role
  name: reader
  apiGroup: rbac.authorization.k8s.io