apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    name: ''
    namespace: ''
    server: https://kubernetes.default.svc
  source:
    path: argocd/argocd
    repoURL: https://github.com/ProjectOrangeJuice/ProjectKubernetes.git
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default

--- 

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  destination:
    name: ''
    namespace: ''
    server: https://kubernetes.default.svc
  source:
    path: argocd/metallb
    repoURL: https://github.com/ProjectOrangeJuice/ProjectKubernetes.git
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default

--- 

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
spec:
  destination:
    name: ''
    namespace: ''
    server: https://kubernetes.default.svc
  source:
    path: argocd/longhorn
    repoURL: https://github.com/ProjectOrangeJuice/ProjectKubernetes.git
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default
