apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: argocd/argocd
    repoURL: https://github.com/ProjectOrangeJuice/ProjectKubernetes.git
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default

--- 

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: metallb
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: argocd/metallb
    repoURL: https://github.com/ProjectOrangeJuice/ProjectKubernetes.git
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default

--- 

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: longhorn
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: argocd/longhorn
    repoURL: https://github.com/ProjectOrangeJuice/ProjectKubernetes.git
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: longhorn-helm
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  sources:
  - repoURL: 'https://charts.longhorn.io'
    chart: longhorn
    targetRevision: 1.8.0
    helm:
      valueFiles:
      - $values/argocd/helm/longhorn.yaml
  - repoURL: 'https://github.com/ProjectOrangeJuice/ProjectKubernetes.git'
    targetRevision: HEAD
    ref: values