apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: argocd/argocd
    repoURL: https://github.com/ProjectOrangeJuice/ProjectKubernetes.git
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true

--- 

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: infra
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: argocd/infra
    repoURL: https://github.com/ProjectOrangeJuice/ProjectKubernetes.git
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true

--- 

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: mealie
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: argocd/mealie
    repoURL: https://github.com/ProjectOrangeJuice/ProjectKubernetes.git
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default

--- 

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: uptime
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: argocd/uptime
    repoURL: https://github.com/ProjectOrangeJuice/ProjectKubernetes.git
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default



