apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: traefik-system
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-system
  source:
    repoURL: 'https://traefik.github.io/charts'
    chart: traefik
    targetRevision: 34.2.0
    helm:
      values: |
        providers:
          kubernetesCRD:
            allowCrossNamespace: true
        dashboard:
          enabled: true
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: nfs-provisioner
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-provisioner
  source:
    repoURL: 'https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner'
    chart: nfs-subdir-external-provisioner
    targetRevision: 4.0.18
    helm:
      values: |
        nfs:
          server: 192.168.10.10
          path: /mnt/export-nfs

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: wiki
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: wiki
  source:
    repoURL: 'https://charts.js.wiki'
    chart: wiki
    targetRevision: 2.2.22
    helm:
      values: |
        postgresql:
          persistence:
            storageClass: nfs-client