
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: longhorn-helm
spec:
  project: default
  destination:
    namespace: kube-system # on talos this has the correct permissions
    server: https://kubernetes.default.svc
  sources:
  - repoURL: 'https://charts.longhorn.io'
    chart: longhorn
    targetRevision: 1.8.0
    helm:
      valueFiles:
      - $values/argocd/helm/longhorn.yaml
  - repoURL: 'https://github.com/ProjectOrangeJuice/ProjectKubernetes.git'
    targetRevision: HEAD
    ref: values