apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: traefik-system
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-system
  source:
    repoURL: 'https://traefik.github.io/charts'
    chart: traefik
    targetRevision: 34.2.0
    helm:
      values: |
        providers:
          kubernetesCRD:
            allowCrossNamespace: true
        dashboard:
          enabled: true
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: nfs-provisioner
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-provisioner
  source:
    repoURL: 'https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner'
    chart: nfs-subdir-external-provisioner
    targetRevision: 4.0.18
    helm:
      values: |
        nfs:
          server: 192.168.100.69
          path: /export/kubernetes

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: nextcloud
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-provisioner
  sources:
    - plugin:
        name: argocd-vault-plugin 
      repoURL: 'https://nextcloud.github.io/all-in-one/'
      chart: nextcloud-aio
      targetRevision: 10.5.0
      helm:
        valuesFiles:
          - $values/nextcloud-values.yaml
    - repoURL: 'https://github.com/ProjectOrangeJuice/ProjectKubernetes.git'
      path: argocd/nextcloud
      ref: values