apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: traefik-system
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  sources:
  - repoURL: 'https://traefik.github.io/charts'
    chart: traefik
    targetRevision: 3.3.3