- name: Check if kubernetes is already running on controller node
  command: kubectl get nodes
  register: k8s_nodes
  ignore_errors: yes

- name: Initialize Kubernetes cluster on controller node if kubernetes is not running
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  when: k8s_nodes.rc != 0

- name: Create .kube directory
  command: mkdir -p /root/.kube

- name: Copy kube config to user home directory
  command: cp /etc/kubernetes/admin.conf /root/.kube/config

- name: Install Cilium CLI
  command: curl -L --remote-name https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz

- name: Extract Cilium CLI
  command: tar xzvf cilium-linux-amd64.tar.gz

- name: Move Cilium CLI to /usr/local/bin
  command: mv cilium /usr/local/bin

- name: Check if cilium is running
  command: kubectl get pods -n kube-system
  register: cilium_pods
  ignore_errors: yes

- name: Install Cilium network plugin if it is not running
  command: cilium install
  when: cilium_pods.rc != 0

- name: Check if flux is installed on controller node
  command: flux --version
  register: flux_version
  ignore_errors: yes

- name: Download the FluxCD installation script
  get_url:
    url: 'https://fluxcd.io/install.sh'
    dest: '/tmp/fluxcd-installer.sh'
    mode: '0755'

  # Define the task to execute the script
- name: Execute the FluxCD installation script
  shell: '/tmp/fluxcd-installer.sh'

- name: Install flux onto kubernetes cluster
  shell: flux bootstrap github --owner={{ github_owner }} --repository=projectkubernetes --branch=main --path=./cluster/flux --personal
  environment:
    GITHUB_TOKEN: "{{ github_token }}"
  when: flux_version.rc != 0