---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`memo.projectkube.com`)
      kind: Rule
      services:
        - name: memo
          port: 5230
